# YAML configuration for ANTs registration to SRI24 atlas

# Input and output paths
atlas_path: /home/mariopasc/Python/Datasets/Meningiomas/ATLAS/sri24_spm8/templates/T1_brain.nii
output_dir: /home/mariopasc/Python/Datasets/Meningiomas/ATLAS/temp_dir_registration # temp dir, will be removed
output_registered: registered.nii.gz
output_mask: registered_mask.nii.gz
output_transform_prefix: transform_
initial_transform: null  # Can be set to a path to initialize from previous transform

# Basic registration parameters
dimension: 3
histogram_matching: false
winsorize_lower_quantile: 0.005
winsorize_upper_quantile: 0.995
number_threads: 5
verbose: true

# Transform stages
transforms: ["Rigid", "Affine", "SyN"]
transform_parameters: 
  - [0.1]
  - [0.1]
  - [0.1, 3.0, 0.0]

# Resolution stages
iterations:
  - [1000, 500, 250, 100]
  - [1000, 500, 250, 100]
  - [100, 70, 50, 20]
shrink_factors:
  - [8, 4, 2, 1]
  - [8, 4, 2, 1]
  - [8, 4, 2, 1]
smoothing_sigmas:
  - [3, 2, 1, 0]
  - [3, 2, 1, 0]
  - [3, 2, 1, 0]

# Metrics
metrics: ["MI", "MI", "MI"] # Let's try without CC
metric_weights: [1.0, 1.0, 1.0]

# Advanced parameters
sampling_strategy: ["Regular", "Regular", "None"]
sampling_percentage: [0.25, 0.25, null]
radius_or_number_of_bins: [32, 32, 4]
convergence_threshold: [1e-6, 1e-6, 1e-6]
convergence_window_size: [10, 10, 10]
sigma_units: ["vox", "vox", "vox"]
write_composite_transform: true