[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[project]
authors = [{name = "Mario Pascual Gonzalez", email = "mario.pg02@gmail.com"}]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  "opencv-python-headless",
  "matplotlib",
  "scikit-image",
  "scipy",
  "pynrrd",
  "SciencePlots",
  "pandas",
  "openpyxl",
  "ipykernel",
  "tqdm",
  "scikit-learn",
  "gstools",
  "pyvista",
  "pyyaml",
]
description = "A Python library that contains all the functions used to perform experiments on neuroimaging data and generate a Meningioma dataset."
keywords = ["neuroimaging", "deep learning", "bioinformatics"]
license = {file = "LICENSE"}
name = "Meningioma"
readme = "README.md"
requires-python = ">=3.9"
version = "0.1.0"

[project.urls]
"Repository" = "https://github.com/MarioPasc/Meningioma"

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line_length = 88
