[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"] # Specify build requirements

[project]
authors = [{name = "Mario Pascual Gonzalez", email = "mario.pg02@gmail.com"}]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  "opencv-python-headless",
  "matplotlib",
  "scikit-image",
  "scipy",
  "pynrrd",
  "SciencePlots",
  "pandas",
  "openpyxl",
  "ipykernel",
  "tqdm",
  "scikit-learn",
  "gstools",
]
description = "A Python library that contains all the functions used to perform experiments on neuroimaging data and generate a Meningioma dataset."
keywords = ["neuroimaging", "deep learning", "bioinformatics"]
license = {file = "LICENSE"}
name = "Meningioma"
readme = "README.md"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 88
[tool.mypy.overrides]

[tool.mypy]
ignore_missing_imports = true
