[project]
name = "Meningioma"
version = "1.0.0"
requires-python = ">=3.10"
description = "Meningioma package harbors every tools used for meningioma characterization and growth prediction."
readme = "README.md"
license = {file = "LICENSE"}
authors = [
  {name = "Mario Pascual González", email = "mpascual@uma.es"},
  {name = "Computational Intelligence and Image Analysis lab (ICAI)"},
  {name = "Hospital Regional Universitario de Málaga"},
]
classifiers = [
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Healthcare Industry",
  "Programming Language :: Python :: 3",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Scientific/Engineering :: Image Recognition",
  "Topic :: Scientific/Engineering :: Medical Science Apps.",
]
keywords = [
  'deep learning',
  'medical image analysis',
  'medical image segmentation',
]
dependencies = [
  "opencv-python-headless",
  "matplotlib",
  "scikit-image",
  "scipy",
  "pynrrd",
  "SciencePlots",
  "pandas",
  "openpyxl",
  "ipykernel",
  "tqdm",
  "scikit-learn",
  "gstools",
  "pyvista",
  "pyyaml",
  "natsort",
  "nipype",
  "SimpleITK",
  "numpy",
  "nibabel",
]

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[project.urls]
"Repository" = "https://github.com/MarioPasc/Meningioma"

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line_length = 88
