# Dataset configuration
paths:
  root: "/home/mariopasc/Python/Datasets/Meningiomas/raw/Meningioma_Adquisition"
  output: "/home/mariopasc/Python/Datasets/Meningiomas/processed/misc"
  atlas_root: "/home/mariopasc/Python/Datasets/Meningiomas/ATLAS/sri24_spm8/templates"

processing:
  threads: 4

# "T1SIN" excluded
modalities:
  RM: ["T1", "T2", "SUSC", "FLAIR"] # T1SIN
  # TC: ["TC"]


preprocessing:
  RM:
    remove_channel:
      channel: 0
    export_nifti: true
    cast_volume: true
    bias_field_correction:
      n4:
        shrink_factor: 4
        max_iterations: 100
        control_points: 6
        bias_field_fwhm: 0.1
    registration:
      sri24:
        enable: true
        config_path: "/home/mariopasc/Python/Projects/Meningioma/src/mgmGrowth/preprocessing/configs/registration_sri24.yaml" 
    brain_extraction:
      universal_mask:
        path: "/home/mariopasc/Python/Datasets/Meningiomas/ATLAS/sri24_spm8/templates/T1_brain.nii"
      fsl_bet:
        frac: 0.5
        robust: true
        vertical_gradient: 0
        skull: false  
      

  TC:
    export_nifti: true
    cast_volume: true
    reorientation:
      orientation: "LPS"
    resample:
      spacing: [1.0, 1.0, 1.0]
    denoise:
      enable: false
      susan:
        brightness_threshold: 0.001
        fwhm: 0.5
        dimension: 3
    brain_extraction:
      apply_smoothing: False
      bet_fractional_intensity: 0.01
      perform_skull_erosion: False
      erosion_radius: 1
    hounsfield_clipping:
      window_width: 80
      window_level: 40
    registration:
      sri24:
        enable: true
        pulse: "T1"
        num_threads: 2
        pulses_to_register: ["TC"]
        config_path: "/home/mariopasc/Python/Projects/Meningioma/src/Meningioma/preprocessing/configs/registration_sri24.yaml" 
    transpose:
      axis: [2, 1, 0]
