# YAML configuration for ANTs → SRI-24 registration
# -------------------------------------------------

# I/O -------------------------------------------------------------------------
atlas_path: /home/mariopasc/Python/Datasets/Meningiomas/ATLAS/sri24_spm8/templates/T1.nii
output_dir: /home/mariopasc/Python/Datasets/Meningiomas/ATLAS/temp_dir_registration
output_registered: registered.nii.gz
output_mask: registered_mask.nii.gz
output_transform_prefix: transform_
initial_transform: null          # optional – seed with an external transform

# Global options --------------------------------------------------------------
dimension: 3
histogram_matching: false
winsorize_lower_quantile: 0.001
winsorize_upper_quantile: 0.999
number_threads: 7
verbose: true
interpolation: BSpline             # NEW – applies to every warped image

# -----------------------------------------------------------------------------#
#  Stage parameter blocks
# -----------------------------------------------------------------------------#

full_registration:                # T1  ➜  template
  transforms: ["Rigid", "Affine"]
  transform_parameters:
    - [0.1]
    - [0.1]
  iterations:
    - [1000, 500, 250, 100]
    - [1000, 500, 250, 100]
  shrink_factors:
    - [8, 4, 2, 1]
    - [8, 4, 2, 1]
  smoothing_sigmas:
    - [3, 2, 1, 0]
    - [3, 2, 1, 0]
  metrics: ["MI", "MI"]
  metric_weights: [1.0, 1.0]
  sampling_strategy: ["Regular", "Regular"]
  sampling_percentage: [0.25, 0.25]
  radius_or_number_of_bins: [32, 32]
  convergence_threshold: [1e-6, 1e-6]
  convergence_window_size: [10, 10]
  sigma_units: ["vox", "vox"]
  write_composite_transform: true

secondary_modality:               # T2 / FLAIR / SWI  ➜  T1
  transforms: ["Rigid", "Affine"]
  transform_parameters:
    - [0.1]
    - [0.1]
  iterations:
    - [1000, 500, 250, 100]
    - [1000, 500, 250, 100]
  shrink_factors:
    - [8, 4, 2, 1]
    - [8, 4, 2, 1]
  smoothing_sigmas:
    - [3, 2, 1, 0]
    - [3, 2, 1, 0]
  metrics: ["MI", "MI"]
  metric_weights: [1.0, 1.0]
  sampling_strategy: ["Regular", "Regular"]
  sampling_percentage: [0.25, 0.25]
  radius_or_number_of_bins: [32, 32]
  convergence_threshold: [1e-6, 1e-6]
  convergence_window_size: [10, 10]
  sigma_units: ["vox", "vox"]
  write_composite_transform: true
